---
name: activitymail
version: 1.25
author:
  - 'David Wheeler <david@justatheory.com>'
abstract: CVS activity notification
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  File::Basename: 0
  Getopt::Std: 0
build_requires:
  Module::Build: 0.2701
recommends:
  File::Spec: 0
  HTML::Entities: 0
  URI::Escape: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
