--- #YAML:1.0
name: activitymail
version: 1.11
license: perl
distribution_type: module
requires:
  File::Basename: 0
  Getopt::Std: 0
recommends:
  File::Spec: 0
build_requires: {}
conflicts: {}
provides: {}
generated_by: Module::Build version 0.20
