--- #YAML:1.0
name: activitymail
version: 1.18
author:
  - David Wheeler <david@wheeler.net>
abstract: CVS activity notification
license: perl
requires:
  File::Basename: 0
  Getopt::Std: 0
recommends:
  File::Spec: 0
provides: {}
generated_by: Module::Build version 0.24
